name: xrex_catalog
description: "X-rex fotoğraftan katalog taslak uygulaması."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.2
  google_mlkit_object_detection: 0.15.0
  google_mlkit_text_recognition: 0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
