name: xrex_catalog
description: "X-rex fotoğraftan katalog taslak uygulaması."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.2
  google_mlkit_object_detection: 0.15.1
  google_mlkit_text_recognition: 0.15.1
  image: ^4.9.1
  tflite_flutter: ^0.12.1
  http: ^1.2.2
  # Web desteği için paketler
  tflite_web: ^0.1.0
  universal_html: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/ml/efficientdet_lite0.tflite
